### PR TITLE
@barcod3 @onekilo79 use dynamic port in new ember of 0 not -1

### PR DESCRIPTION
**Pull request by barcod3**
The way to create a dynamic port has changed it is now 0 not -1

### CODE REVIEW

**Comment by benkiefer** [comment]
Thanks for the PR. Quick question. Is there a particular version of ember where you were seeing this change? We are using 2.6.x and it's working fine here.

I will get this merged and a new release cut tonight. I just want to make sure I bump the version of the plugin accordingly since this a breaking-ish change.

**Comment by iNaD** [comment]
Isn't this more related to newer Node versions, than it is to ember? See #16
Correct me, if I'm wrong ;)

**Comment by benkiefer** [comment]
Yup, @iNaD that's what I'm hoping.  Sounds like I just need to go down the route of making the test command and args configurable to that folks can do whatever they want.

For example, we use ember exam here for our builds which dramatically sped things up.

I'll just do reasonable defaults of what we have today.

**Comment by benkiefer** [comment]
I've cut a release for version 3.1.0 based on my comments above. You can now configure the `testCommand` and `testArguments` properties in order to customize the command the way you see fit or try out new configurations. Personally, I recommend looking at the ember exam plugin. we use it quite a bit at work and have sped up our larger ember builds significantly.

To use the ember exam plugin with a test-port of 0 instead of the default functionality you would do something like:

```
apply plugin: "com.kiefer.gradle.embercli"

embercli {
     testCommand = "exam"
     testArguments = ["--split=5", "--parallel", "--test-port=0"]
}
```

I'm going to decline the PR, but I appreciate you guys letting me know what issues you are running into and submitting a fix. Hopefully this is a flexible option that works for everyone.

A quick note, this change is non-breaking. The default for `testCommand` is `test` and the default for `testArguments` is `["--test-port=-1"]`

**Pull request closed without merging**
